
# cloudbuild.yaml — Google Cloud Build CI/CD pipeline
# Triggers automatically on push to main branch.
#
# Setup:
#   gcloud builds triggers create github \
#     --repo-name=zomato-ai --repo-owner=YOUR_GITHUB_ORG \
#     --branch-pattern='^main$' \
#     --build-config=cloudbuild.yaml

steps:
  # ── Step 1: Build the Docker image with BuildKit inline caching ───────────
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - build
      - "--platform=linux/amd64"
      - "--cache-from=${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:cache"
      - "--build-arg=BUILDKIT_INLINE_CACHE=1"
      - "--tag=${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA"
      - "--tag=${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # ── Step 2: Push commit-sha tag ───────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: "push-sha"
    args:
      - push
      - "${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA"
    waitFor: ["build"]

  # ── Step 3: Push latest + cache tag ──────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      - push
      - "${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
    waitFor: ["push-sha"]

  # ── Step 4: Deploy to Cloud Run ───────────────────────────────────────────
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - "--image=${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--port=8080"
      - "--allow-unauthenticated"
      - "--memory=2Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--concurrency=80"
      - "--timeout=300"
      - "--set-env-vars=STREAMLIT_SERVER_PORT=8080,STREAMLIT_SERVER_HEADLESS=true,HF_HOME=/tmp/hf_cache"
      - "--labels=app=zomato-ai,env=production,commit=$SHORT_SHA"
    waitFor: ["push-latest"]

  # ── Step 5: Smoke-test the deployed service ───────────────────────────────
  - name: "curlimages/curl:latest"
    id: "smoke-test"
    entrypoint: sh
    args:
      - "-c"
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE} \
          --region=${_REGION} --format='value(status.url)')
        echo "Smoke-testing: $SERVICE_URL/_stcore/health"
        sleep 15
        curl -sf "$SERVICE_URL/_stcore/health" && echo "✅ HEALTHY" || (echo "❌ NOT READY" && exit 1)
    waitFor: ["deploy"]

# ── Substitution defaults (override via trigger config or --substitutions) ─
substitutions:
  _REGION:  "us-central1"
  _SERVICE: "zomato-ai-recommender"
  _REPO:    "zomato-ai"
  _AR_HOST: "${_REGION}-docker.pkg.dev"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"

images:
  - "${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA"
  - "${_AR_HOST}/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
